global ad_project_params

set ad_project_params(FPGA_ID) 0x04b31093
set ad_project_params(FW_ID) 0x00000000
set ad_project_params(FW_VER) 0x00000100
set ad_project_params(BOARD_ID) 0x10ee9076
set ad_project_params(BOARD_VER) 0x01000000
set ad_project_params(BUILD_DATE) 0x17320231
set ad_project_params(GIT_HASH) 0x37f26075
set ad_project_params(RELEASE_INFO) 0x00000000
set ad_project_params(IF_COUNT) 1
set ad_project_params(PORTS_PER_IF) 1
set ad_project_params(SCHED_PER_IF) 1
set ad_project_params(PORT_COUNT) 1
set ad_project_params(CLK_PERIOD_NS_NUM) 4
set ad_project_params(CLK_PERIOD_NS_DENOM) 1
set ad_project_params(PTP_CLK_PERIOD_NS_NUM) 32
set ad_project_params(PTP_CLK_PERIOD_NS_DENOM) 5
set ad_project_params(PTP_CLOCK_PIPELINE) 0
set ad_project_params(PTP_CLOCK_CDC_PIPELINE) 0
set ad_project_params(PTP_SEPARATE_TX_CLOCK) 0
set ad_project_params(PTP_SEPARATE_RX_CLOCK) 0
set ad_project_params(PTP_PORT_CDC_PIPELINE) 0
set ad_project_params(PTP_PEROUT_ENABLE) 1
set ad_project_params(PTP_PEROUT_COUNT) 1
set ad_project_params(EVENT_QUEUE_OP_TABLE_SIZE) 32
set ad_project_params(TX_QUEUE_OP_TABLE_SIZE) 32
set ad_project_params(RX_QUEUE_OP_TABLE_SIZE) 32
set ad_project_params(CQ_OP_TABLE_SIZE) 32
set ad_project_params(EQN_WIDTH) 6
set ad_project_params(TX_QUEUE_INDEX_WIDTH) 13
set ad_project_params(RX_QUEUE_INDEX_WIDTH) 8
set ad_project_params(CQN_WIDTH) 14
set ad_project_params(EQ_PIPELINE) 3
set ad_project_params(TX_QUEUE_PIPELINE) 4
set ad_project_params(RX_QUEUE_PIPELINE) 3
set ad_project_params(CQ_PIPELINE) 5
set ad_project_params(TX_DESC_TABLE_SIZE) 32
set ad_project_params(RX_DESC_TABLE_SIZE) 32
set ad_project_params(RX_INDIR_TBL_ADDR_WIDTH) 8
set ad_project_params(TX_SCHEDULER_OP_TABLE_SIZE) 32
set ad_project_params(TX_SCHEDULER_PIPELINE) 4
set ad_project_params(TDMA_INDEX_WIDTH) 6
set ad_project_params(PTP_TS_ENABLE) 1
set ad_project_params(PTP_TS_FMT_TOD) 0
set ad_project_params(PTP_TS_WIDTH) 48
set ad_project_params(TX_CPL_ENABLE) 1
set ad_project_params(TX_CPL_FIFO_DEPTH) 32
set ad_project_params(TX_TAG_WIDTH) 16
set ad_project_params(TX_CHECKSUM_ENABLE) 1
set ad_project_params(RX_HASH_ENABLE) 1
set ad_project_params(RX_CHECKSUM_ENABLE) 1
set ad_project_params(PFC_ENABLE) 1
set ad_project_params(LFC_ENABLE) 1
set ad_project_params(MAC_CTRL_ENABLE) 0
set ad_project_params(TX_FIFO_DEPTH) 131072
set ad_project_params(RX_FIFO_DEPTH) 131072
set ad_project_params(MAX_TX_SIZE) 9214
set ad_project_params(MAX_RX_SIZE) 9214
set ad_project_params(TX_RAM_SIZE) 131072
set ad_project_params(RX_RAM_SIZE) 131072
set ad_project_params(DDR_ENABLE) 0
set ad_project_params(DDR_CH) 1
set ad_project_params(DDR_GROUP_SIZE) 1
set ad_project_params(AXI_DDR_DATA_WIDTH) 256
set ad_project_params(AXI_DDR_ADDR_WIDTH) 32
set ad_project_params(AXI_DDR_STRB_WIDTH) 32
set ad_project_params(AXI_DDR_ID_WIDTH) 8
set ad_project_params(AXI_DDR_AWUSER_ENABLE) 0
set ad_project_params(AXI_DDR_WUSER_ENABLE) 0
set ad_project_params(AXI_DDR_BUSER_ENABLE) 0
set ad_project_params(AXI_DDR_ARUSER_ENABLE) 0
set ad_project_params(AXI_DDR_RUSER_ENABLE) 0
set ad_project_params(AXI_DDR_MAX_BURST_LEN) 256
set ad_project_params(AXI_DDR_NARROW_BURST) 0
set ad_project_params(AXI_DDR_FIXED_BURST) 0
set ad_project_params(AXI_DDR_WRAP_BURST) 0
set ad_project_params(HBM_ENABLE) 0
set ad_project_params(HBM_CH) 1
set ad_project_params(HBM_GROUP_SIZE) 1
set ad_project_params(AXI_HBM_DATA_WIDTH) 256
set ad_project_params(AXI_HBM_ADDR_WIDTH) 32
set ad_project_params(AXI_HBM_STRB_WIDTH) 32
set ad_project_params(AXI_HBM_ID_WIDTH) 8
set ad_project_params(AXI_HBM_AWUSER_ENABLE) 0
set ad_project_params(AXI_HBM_AWUSER_WIDTH) 1
set ad_project_params(AXI_HBM_WUSER_ENABLE) 0
set ad_project_params(AXI_HBM_WUSER_WIDTH) 1
set ad_project_params(AXI_HBM_BUSER_ENABLE) 0
set ad_project_params(AXI_HBM_BUSER_WIDTH) 1
set ad_project_params(AXI_HBM_ARUSER_ENABLE) 0
set ad_project_params(AXI_HBM_ARUSER_WIDTH) 1
set ad_project_params(AXI_HBM_RUSER_ENABLE) 0
set ad_project_params(AXI_HBM_RUSER_WIDTH) 1
set ad_project_params(AXI_HBM_MAX_BURST_LEN) 256
set ad_project_params(AXI_HBM_NARROW_BURST) 0
set ad_project_params(AXI_HBM_FIXED_BURST) 0
set ad_project_params(AXI_HBM_WRAP_BURST) 0
set ad_project_params(APP_ENABLE) 1
set ad_project_params(APP_ID) 0x12340001
set ad_project_params(APP_CTRL_ENABLE) 1
set ad_project_params(APP_DMA_ENABLE) 1
set ad_project_params(APP_AXIS_DIRECT_ENABLE) 1
set ad_project_params(APP_AXIS_SYNC_ENABLE) 1
set ad_project_params(APP_AXIS_IF_ENABLE) 1
set ad_project_params(APP_STAT_ENABLE) 1
set ad_project_params(APP_GPIO_IN_WIDTH) 32
set ad_project_params(APP_GPIO_OUT_WIDTH) 32
set ad_project_params(AXI_DATA_WIDTH) 512
set ad_project_params(AXI_ADDR_WIDTH) 64
set ad_project_params(AXI_STRB_WIDTH) 64
set ad_project_params(AXI_ID_WIDTH) 8
set ad_project_params(DMA_IMM_ENABLE) 0
set ad_project_params(DMA_IMM_WIDTH) 32
set ad_project_params(DMA_LEN_WIDTH) 16
set ad_project_params(DMA_TAG_WIDTH) 16
set ad_project_params(RAM_ADDR_WIDTH) 17
set ad_project_params(RAM_PIPELINE) 2
set ad_project_params(AXI_DMA_MAX_BURST_LEN) 256
set ad_project_params(AXI_DMA_READ_USE_ID) 0
set ad_project_params(AXI_DMA_WRITE_USE_ID) 1
set ad_project_params(AXI_DMA_READ_OP_TABLE_SIZE) 256
set ad_project_params(AXI_DMA_WRITE_OP_TABLE_SIZE) 256
set ad_project_params(IRQ_COUNT) 8
set ad_project_params(AXIL_CTRL_DATA_WIDTH) 32
set ad_project_params(AXIL_CTRL_ADDR_WIDTH) 24
set ad_project_params(AXIL_CTRL_STRB_WIDTH) 4
set ad_project_params(AXIL_IF_CTRL_ADDR_WIDTH) 24
set ad_project_params(AXIL_CSR_ADDR_WIDTH) 19
set ad_project_params(AXIL_CSR_PASSTHROUGH_ENABLE) 0
set ad_project_params(RB_NEXT_PTR) 0x00001000
set ad_project_params(AXIL_APP_CTRL_DATA_WIDTH) 32
set ad_project_params(AXIL_APP_CTRL_ADDR_WIDTH) 24
set ad_project_params(AXIL_APP_CTRL_STRB_WIDTH) 4
set ad_project_params(AXIS_DATA_WIDTH) 512
set ad_project_params(AXIS_KEEP_WIDTH) 64
set ad_project_params(AXIS_SYNC_DATA_WIDTH) 512
set ad_project_params(AXIS_IF_DATA_WIDTH) 512
set ad_project_params(AXIS_TX_USER_WIDTH) 17
set ad_project_params(AXIS_RX_USER_WIDTH) 49
set ad_project_params(AXIS_RX_USE_READY) 0
set ad_project_params(AXIS_TX_PIPELINE) 4
set ad_project_params(AXIS_TX_FIFO_PIPELINE) 4
set ad_project_params(AXIS_TX_TS_PIPELINE) 4
set ad_project_params(AXIS_RX_PIPELINE) 4
set ad_project_params(AXIS_RX_FIFO_PIPELINE) 4
set ad_project_params(STAT_ENABLE) 1
set ad_project_params(STAT_DMA_ENABLE) 1
set ad_project_params(STAT_AXI_ENABLE) 1
set ad_project_params(STAT_INC_WIDTH) 24
set ad_project_params(STAT_ID_WIDTH) 12
set ad_project_params(DMA_ADDR_WIDTH_APP) 64
set ad_project_params(RAM_SEL_WIDTH_APP) 3
set ad_project_params(RAM_SEG_COUNT_APP) 2
set ad_project_params(RAM_SEG_DATA_WIDTH_APP) 512
set ad_project_params(RAM_SEG_BE_WIDTH_APP) 64
set ad_project_params(RAM_SEG_ADDR_WIDTH_APP) 10
set ad_project_params(AXIS_SYNC_KEEP_WIDTH_APP) 64
set ad_project_params(AXIS_SYNC_TX_USER_WIDTH_APP) 17
set ad_project_params(AXIS_SYNC_RX_USER_WIDTH_APP) 49
set ad_project_params(AXIS_IF_KEEP_WIDTH_APP) 64
set ad_project_params(AXIS_IF_TX_ID_WIDTH_APP) 13
set ad_project_params(AXIS_IF_RX_ID_WIDTH_APP) 1
set ad_project_params(AXIS_IF_TX_DEST_WIDTH_APP) 4
set ad_project_params(AXIS_IF_RX_DEST_WIDTH_APP) 9
set ad_project_params(AXIS_IF_TX_USER_WIDTH_APP) 17
set ad_project_params(AXIS_IF_RX_USER_WIDTH_APP) 49
set ad_project_params(TDMA_BER_ENABLE) 0
set ad_project_params(QSFP_CNT) 1
set ad_project_params(PORT_MASK) 0
set ad_project_params(ETH_RX_CLK_FROM_TX) 0
set ad_project_params(ETH_RS_FEC_ENABLE) 1
set ad_project_params(DMA_ADDR_WIDTH) 64
set ad_project_params(RAM_SEL_WIDTH) 3
set ad_project_params(RAM_SEG_COUNT) 2
set ad_project_params(RAM_SEG_DATA_WIDTH) 512
set ad_project_params(RAM_SEG_BE_WIDTH) 64
set ad_project_params(RAM_SEG_ADDR_WIDTH) 10
set ad_project_params(AXIS_SYNC_KEEP_WIDTH) 64
set ad_project_params(AXIS_SYNC_TX_USER_WIDTH) 17
set ad_project_params(AXIS_SYNC_RX_USER_WIDTH) 49
set ad_project_params(AXIS_IF_KEEP_WIDTH) 64
set ad_project_params(AXIS_IF_TX_ID_WIDTH) 13
set ad_project_params(AXIS_IF_RX_ID_WIDTH) 1
set ad_project_params(AXIS_IF_TX_DEST_WIDTH) 4
set ad_project_params(AXIS_IF_RX_DEST_WIDTH) 9
set ad_project_params(AXIS_IF_TX_USER_WIDTH) 17
set ad_project_params(AXIS_IF_RX_USER_WIDTH) 49

set ad_project_params(INPUT_WIDTH) 128
set ad_project_params(INPUT_CHANNELS) 8

set ad_project_params(OUTPUT_WIDTH) 128
set ad_project_params(OUTPUT_CHANNELS) 8
